
name: check env variables
on: [push]
env:
  yaml_var: ${{ 'his is yaml var in brackets' }}
jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: check env variables values
        run: |
            echo $GITHUB_REF
            echo $yaml_var
      - name: 2nd
        run: |
            echo '${{ github.ref }}'
            echo $yaml_var
      - name: from dynamic file
        run: |
          echo "VNEW_ENV_AR=$(date)" >> "$GITHUB_ENV"
          echo "yaml_var=$RANDOM" >> "$GITHUB_ENV"
          echo "::debug::Set the Octocat variable"
          # echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: from dynamic file
        run: |
            echo $VNEW_ENV_AR
            echo $yaml_var
            echo ${{ vars.TEST_PROD_VARIABLE }}
            echo "secret ${{ secrets.ENV_SECRET }}
    
