
name: check env variables
on: [push]
env:
  yaml_var: ${{ this is yaml var in brackets }}
jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: check env variables values
        run: |
            echo $GITHUB_REF
            echo $yaml_var
      - name: 2nd
        run: |
            echo '${{ github.ref }}'
            echo $yaml_var

    
