name: manual_expression
on:
  workflow_dispatch:
    inputs:
      string1:
        type: string
        required: true
        default: shaina
jobs:
  first_job:
    runs_on: ubuntu_latest
      
    steps:
      - run: |
          echo "string value ${{inputs.string1}}"
      - run: echo "hi"
        if: ${{inputs.string1 == 'shaina' }} || failure()
