name: dispatch receiver

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: expressions
      id: expressions
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run:
        echo ${{1}}
        echo ${{null}}
        echo ${{true}}
        echo ${{'a string'}}
        echo ${{ true && false}}
        echo ${{ true || (true && false) }}
