name: manual
on:
  workflow_dispatch:
    inputs:
      string1:
        type: string
        required: true
        default: shaina
jobs:
  firstjob:
    runs-on: ubuntu_latest
    steps:
      - run: |
          echo "string value ${{inputs.string1}}"
