name: newfile
on: 
  push:
  pull_request:
    types: [opened,assigned]
    
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: run-cmd
      run: |
        pwd
        ls -a
        echo $GITHUB_SHA
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE
