name: Generate Index HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      generate_html:
        description: 'Generate index.html'
        required: true
        default: 'true'

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Generate HTML
        run: |
          echo "<html><body><h1>Welcome to my website!</h1></body></html>" > index.html
